name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with: 
          python version: '3.10'
      - name: Install Dependecies
        run: |
          python -m install pip --upgarde pip
          pip install pyyaml
      - name: Run Fedd Generator
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name 'Gianni-Lauritz Grubert'
          git config user.email animalibera@mail.de
          git add .
          git commit -m "Modified Feed"
          git push
